tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface": "#f7f9fe",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e2e7",
        "surface-bright": "#f7f9fe",
        "surface-tint": "#1e60a3",
        "tertiary-fixed-dim": "#8bd5bf",
        "surface-dim": "#d8dadf",
        "on-primary-fixed-variant": "#004883",
        "deep-navy": "#00234B",
        "on-tertiary-container": "#88d2bc",
        "on-secondary-fixed": "#001b3d",
        "surface-container-high": "#e6e8ed",
        "success-teal": "#277462",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#455f8a",
        "primary": "#126ae2",
        "outline": "#727782",
        "on-secondary-fixed-variant": "#2c4771",
        "on-surface-variant": "#424750",
        "background": "#edf2f4",
        "secondary-fixed-dim": "#adc7f8",
        "secondary-container": "#b2cdfe",
        "error-container": "#ffdad6",
        "pure-white": "#ffffff",
        "surface-container-highest": "#e0e2e7",
        "tertiary-container": "#005c4b",
        "on-secondary-container": "#3c5781",
        "inatel-blue": "#126ae2",
        "inverse-surface": "#2d3135",
        "on-primary": "#ffffff",
        "tertiary": "#004236",
        "inverse-primary": "#a3c9ff",
        "on-surface": "#181c20",
        "on-primary-fixed": "#001c39",
        "on-tertiary-fixed": "#002019",
        "primary-fixed-dim": "#a3c9ff",
        "surface-container": "#eceef3",
        "on-error-container": "#93000a",
        "on-primary-container": "#9ec6ff",
        "primary-fixed": "#d3e3ff",
        "error": "#ba1a1a",
        "on-background": "#181c20",
        "primary-container": "#126ae2",
        "surface-container-low": "#f2f4f9",
        "inverse-on-surface": "#eff1f6",
        "tertiary-fixed": "#a6f1db",
        "on-tertiary-fixed-variant": "#005142",
        "outline-variant": "#c2c6d2",
        "secondary-fixed": "#d6e3ff",
        "background-alt": "#edf2f4"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-max-width": "1200px",
        "margin-desktop": "32px",
        "gutter": "24px",
        "stack-lg": "24px",
        "stack-sm": "4px",
        "base": "8px",
        "stack-md": "12px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "label-lg": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "body-sm": ["Nunito Sans"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "body-lg": ["Nunito Sans"],
        "body-md": ["Nunito Sans"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"]
      },
      "fontSize": {
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
};
